name: dmx_usb_pro
description: A Dart driver package for ENTTEC DMX USB PRO running on Windows
version: 1.0.0
repository: https://github.com/espresso3389/dmx_usb_pro

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
